[tools]
atuin = "18.10.0"
bat = "0.26.0"
"cargo:eza" = "0.23.4"
"cargo:fd-find" = "10.3.0"
conftest = "0.63.0"
difftastic = "0.65.0"
fd = "10.3.0"
fzf = "0.66.1"
gcloud = "540.0.0"
"github:jonasvinther/medusa" = "v0.7.3"
"github:lemonade-command/lemonade" = "1.1.1"
go = "1.25.1"
helix = "25.07.1"
jc = "1.25.6"
jless = "0.9.0"
kube-capacity = "0.8.0"
neovim = "0.11.4"
node = "lts"
opa = "1.9.0"
"pipx:tmux-python/tmuxp" = "v1.56.0"
python = "3.13.7"
ripgrep = "15.1.0"
starship = "1.24.0"
terraform = "latest"
terraform-docs = "0.20.0"
uv = "0.8.23"
yazi = "25.5.31"
